# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbfc8161af0a5edfcca8cb2d9f7ce1db21ff2be828becb89d545a2b6f0068ead32ad58647e6b17ea6a91dff25fcecc87a676bb7b280030c3e1cf8aa704bf70c7

test:
  secret_key_base: 6c63a2422068cfb6b742e35b72d98dff2e82d2b1c76c0bd5ebf8cf414f1f7e7a2348f79673b0d75224db2ef224d9d6c5716b3c09d323f80a2f42ad00e48c0d4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
